imfil_optset <- function(){
                        res <- list()
     res$add_new_directions <- c()
       res$armijo_reduction <- 0.5000
       res$complete_history <- 1
          res$custom_scales <- c()
         res$executive_data <- c()
    res$executive_data_flag <- 0
     res$executive_function <- c()
              res$executive <- 0
           res$explore_data <- c()
      res$explore_data_flag <- 0
       res$explore_function <- c()
                res$explore <- 0
         res$extra_argument <- 0
        res$extra_arg_value <- c()
                 res$fscale <- -1.2000
         res$function_delta <- -1
          res$stencil_delta <- -1
          res$least_squares <- 0
     res$limit_quasi_newton <- 1
                  res$maxit <- 50
               res$maxitarm <- 3
                res$maxfail <- 3
            res$noise_aware <- 0
               res$parallel <- 0
                  res$quasi <- 1
         res$random_stencil <- 0
            res$scale_aware <- 0
             res$scalestart <- 1
             res$scaledepth <- 7
        res$simple_function <- 0
         res$smooth_problem <- 0
                res$stencil <- 0
           res$stencil_wins <- 0
                 res$target <- -100000000
                res$termtol <- 0.0100
                res$svarmin <- 0
                res$verbose <- 0
               res$vstencil <- c()
  res             
}
